%   Project video bounding boxes from events for the frame with this TimeCs.
    TheseRows = (BBoxesEvents.V51Frame == FrameCount);
	BBSubset = BBoxesEvents(TheseRows,:);
	nrows = size(BBSubset, 1);
	if (nrows > 0)
%       Add bounding boxes to the image.
        n = 1;
        while n <= nrows
            img = insertShape(img, 'Rectangle',...
                                [BBSubset.TLCol(n) BBSubset.TLRow(n) ...
                                (BBSubset.BRCol(n) - BBSubset.TLCol(n)) ...
                                (BBSubset.BRRow(n) - BBSubset.TLRow(n))], ...
                                'Color', 'white', 'LineWidth', 3);
            img = insertText(img, [BBSubset.TLCol(n) BBSubset.TLRow(n)], ...
                                num2str(BBSubset.EventNo(n)), ...
                                'TextColor', 'white', 'FontSize', 18, ...
                                'BoxOpacity', 0, 'AnchorPoint', 'LeftBottom');
            n = n + 1;
        end
	end
